[build]
  functions = "functions/"
  
[[headers]]
  for = "/*"

[headers.values]
  Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "https://bd-finance-api.herokuapp.com/:splat"
  status = 200