[build]
base = "."
command = "npm run build"
publish = "./build/"

[build.environment]
REACT_APP_API_URL = "https://bd-finance-api.herokuapp.com/"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200