[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[redirects]]
    from = "/autenticar"
    to = "https://bd-finance-api.herokuapp.com/api/v1/usuario/autenticar"
    status = 200
    force = true